# Site settings
title: MengYang Liu`s  Website
email: lixizhi@yeah.net
description: MengYang's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: lmy0412
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/lmy0412/lmy0412.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/lmy0412/lmy0412.github.io/new/master
#########################################

# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: lmy0412
disqus_url: "http://lmy0412.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
